<? 
$_lang ['help_page_title'] = 'Допомога та підтримка';
$_lang ['help_main_head'] = 'MODX тут для вас';
$_lang ['help_main_subhead'] = 'Дивіться нижче, якщо хочете отримати допомогу для вашого MODX проекту <br> Докладніша інформація на <a href="http://modx.com/support"> modx.com/support</ a> або по телефону +1 (469) 777-6639 ';
$_lang ['forums'] = 'Форуми';
$_lang ['forums_title'] = 'Форуми MODX спільноти';
$_lang ['forums_description'] = 'Безкоштовна допомога від спільноти';
$_lang ['forums_link'] = 'http://forums.modx.com/';
$_lang ['docs'] = 'Документація';
$_lang ['docs_title'] = 'Читайте Казкове (MODX) Керівництво';
$_lang ['docs_description'] = 'Офіційна документація MODX';
$_lang ['docs_link'] = 'http://rtfm.modx.com/';
$_lang ['bugs'] = 'Трекер помилок';
$_lang ['bugs_title'] = 'Шліть повідомлення про помилки і нові функції';
$_lang ['bugs_description'] = 'Знайшли проблему? Дайте нам знати! ';
$_lang ['bugs_link'] = 'https://github.com/modxcms/revolution/issues';
$_lang ['support'] = 'Платна підтримка';
$_lang ['support_title'] = 'Купіть квиток екстреної підтримки прямо зараз';
$_lang ['support_description'] = 'Пріоритетна підтримка від творців';
$_lang ['support_link'] = 'http://modx.com/modx-support/';
$_lang ['email_placeholder'] = 'you@example.com';
$_lang ['email_sub'] = 'Будь в курсі з MODX';
$_lang ['email_sub_description'] = 'Підпишіться на <b> MODX Новини </ b>, щоб отримувати всі важливі новини про MODX. Просто введіть ваш email нижче - ми обіцяємо ніколи не розсилати спам. ';
$_lang ['email_sub_button'] = 'Підписатися';
$_lang ['social_follows'] = 'Ви також можете <b> стежити за MODX </ b> по цих каналах.';
$_lang ['follow'] = 'Слідкуйте за MODX';
$_lang ['like'] = 'Лайкнути MODX';
$_lang ['circle'] = 'Додати MODX в круги';
$_lang ['help_about'] = 'Використовуване вами ПЗ MODX® є результатом взаємодії дивовижної спільноти користувачів, прихильників і розробників. З 2004 року MODX спонсорується і управляється командою розробників, фінансування поточної роботи здійснюється через платну підтримку і розробку додаткових платних функцій. Ви можете <a href="http://modx.com/support/" class="supportTicket"> купити підтримку від творців </a>, щоб отримати 1 годину екстреної допомоги (або 2 години непріоритетної підтримки). Або <a href="mailto:hello@modx.com?subject=MODX Manager Inquiry"> напишіть нам </a>, якщо у вас є інше питання про MODX в загальному. ';
$_lang ['help_credit'] = 'MODX & mdash; вільне програмне забезпечення з відкритим вихідним кодом під ліцензією <a href="http://www.gnu.org/licenses/gpl-2.0.html" target="_blank"> GPL version 2.0 </a> або вище. Авторські права (Copyright) 2004-2014 ТОВ "MODX" (MODX, LLC). "MODX" є зареєстрованою торговою маркою. Робіть правильні речі & mdash; будь ласка, зберігайте цю та іншу інформацію на цій сторінці без змін. ';