<? 
$_lang ['database_charset'] = 'Кодування бази даних';
$_lang ['database_name'] = 'Ім\'я бази даних';
$_lang ['database_server'] = 'Сервер бази даних';
$_lang ['database_tables'] = 'Таблиці бази даних';
$_lang ['database_optimize'] = 'Оптимізувати базу даних';
$_lang ['database_table_clickhere'] = 'Натисніть тут';
$_lang ['database_table_clickbackup'] = 'для створення та скачування резервної копії вибраних таблиць';
$_lang ['database_table_datasize'] = 'Розмір даних';
$_lang ['database_table_droptablestatements'] = 'Додати команди DROP TABLE.';
$_lang ['database_table_effectivesize'] = 'Реальний розмір';
$_lang ['database_table_indexsize'] = 'Розмір індексу';
$_lang ['database_table_overhead'] = 'Перевитрата';
$_lang ['database_table_reserved'] = 'Зарезервовано'; // sqlsrv
$_lang ['database_table_records'] = 'Записів';
$_lang ['database_table_tablename'] = 'Ім\'я таблиці';
$_lang ['database_table_totalsize'] = 'Загальний розмір';
$_lang ['database_table_totals'] = 'Разом:';
$_lang ['database_table_unused'] = 'Не використано'; // sqlsrv
$_lang ['database_type'] = 'Тип бази даних';
$_lang ['database_version'] = 'Версія бази даних';
$_lang ['extjs_version'] = 'Версія <a href="http://extjs.com/" target="_blank"> ExtJS </a>';
$_lang ['localtime'] = 'Місцевий час';
$_lang ['magpie_version'] = 'Версія <a href="http://magpierss.sourceforge.net/" target="_blank"> MagpieRSS </a>';
$_lang ['modx_version'] = 'Версія MODX';
$_lang ['onlineusers_action'] = 'Дія';
$_lang ['onlineusers_actionid'] = 'ID дії';
$_lang ['onlineusers_ipaddress'] = 'IP-адресу користувача';
$_lang ['onlineusers_lasthit'] = 'Останнє відвідування';
$_lang ['onlineusers_message'] = 'Цей список показує всіх активних користувачів за останні 20 хвилин (поточний час:';
$_lang ['onlineusers_title'] = 'Користувачі онлайн';
$_lang ['onlineusers_user'] = 'Користувач';
$_lang ['onlineusers_userid'] = 'ID користувача';
$_lang ['optimize_table'] = 'Для оптимізації таблиці натисніть сюди';
$_lang ['optimize_table_err'] = 'Помилка оптимізації таблиці';
$_lang ['phpmailer_version'] = 'Версія <a href="https://github.com/PHPMailer/PHPMailer" target="_blank"> PHPMailer </a>';
$_lang ['server'] = 'Сервер';
$_lang ['servertime'] = 'Серверний час';
$_lang ['serveroffset'] = 'Зсув серверного часу';
$_lang ['smarty_version'] = 'Версія <a href="http://smarty.net/" target="_blank"> Smarty </a>';
$_lang ['sysinfo_desc'] = 'Тут ви можете переглядати загальну інформацію про середовище, в якій працює MODX.';
$_lang ['view_sysinfo'] = 'Інформація про систему';
$_lang ['table_prefix'] = 'Префікс таблиці';
$_lang ['truncate_table'] = 'Для очищення таблиці натисніть сюди';
$_lang ['truncate_table_err'] = 'Помилка очищення таблиці';
$_lang ['version_codename'] = 'Кодове ім\'я версії';